language: java

jdk:
  - oraclejdk8

install: true

branches:
  only:
    - master
    - develop
before_script:
  - mkdir build
  - chmod +x gradlew
script:
  - ./gradlew build -x test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    