package pr0.ves.eliteboy.elitedangerous.companionapi

import com.google.gson.annotations.SerializedName

enum class JournalTypeEnum(val type: Int) {
    Unknown(0),
    AfmuRepairs(3),
    ApproachSettlement(5),
    Bounty(10),
    BuyAmmo(20),
    BuyDrones(30),
    BuyExplorationData(40),
    BuyTradeData(50),
    CapShipBond(60),
    Cargo(63),
    ChangeCrewRole(65),
    ClearSavedGame(70),
    CockpitBreached(80),
    CollectCargo(90),
    CommitCrime(100),
    CommunityGoal(109),
    CommunityGoalJoin(110),
    CommunityGoalReward(120),
    CommunityGoalDiscard(1040),
    Continued(125),
    CrewAssign(126),
    CrewFire(127),
    CrewHire(128),
    CrewLaunchFighter(1268),
    CrewMemberJoins(1270),
    CrewMemberQuits(1280),
    CrewMemberRoleChange(1285),
    DataScanned(1030),
    DatalinkScan(130),
    DatalinkVoucher(1020),
    Died(140),
    Docked(145),
    DockFighter(150),
    DockingCancelled(160),
    DockingDenied(170),
    DockingGranted(180),
    DockingRequested(190),
    DockingTimeout(200),
    DockSRV(210),
    EjectCargo(220),
    EndCrewSession(225),
    EngineerApply(230),
    EngineerContribution(235),
    EngineerCraft(240),
    EngineerProgress(250),
    EscapeInterdiction(260),
    FactionKillBond(270),
    FetchRemoteModule(1000),
    FSDJump(280),
    FuelScoop(290),
    Fileheader(300),
    Friends(305),
    HeatDamage(310),
    HeatWarning(320),
    HullDamage(330),
    Interdicted(340),
    Interdiction(350),
    JetConeBoost(354),
    JetConeDamage(355),
    JoinACrew(356),
    KickCrewMember(357),
    LaunchFighter(360),
    LaunchSRV(370),
    Liftoff(380),
    LoadGame(390),
    Loadout(395),
    Location(400),
    MassModuleStore(1010),
    MarketBuy(410),
    MarketSell(420),
    MaterialCollected(430),
    MaterialDiscarded(440),
    MaterialDiscovered(450),
    Materials(455),
    MiningRefined(460),
    MissionAbandoned(470),
    MissionAccepted(480),
    MissionCompleted(490),
    MissionFailed(500),
    MissionRedirected(505),
    ModuleBuy(510),
    ModuleRetrieve(515),
    ModuleSell(520),
    ModuleSellRemote(990),
    ModuleStore(525),
    ModuleSwap(530),
    Music(535),
    NavBeaconScan(538),
    NewCommander(540),
    Passengers(545),
    PayFines(550),
    PayLegacyFines(560),
    PowerplayCollect(570),
    PowerplayDefect(580),
    PowerplayDeliver(590),
    PowerplayFastTrack(600),
    PowerplayJoin(610),
    PowerplayLeave(620),
    PowerplaySalary(630),
    PowerplayVote(640),
    PowerplayVoucher(650),
    Progress(660),
    Promotion(670),
    PVPKill(675),
    QuitACrew(677),
    Rank(680),
    RebootRepair(690),
    ReceiveText(700),
    RedeemVoucher(710),
    RefuelAll(720),
    RefuelPartial(730),
    Repair(740),
    RepairAll(745),
    RepairDrone(747),
    RestockVehicle(750),
    Resurrect(760),
    Scan(770),
    Scanned(772),
    ScientificResearch(775),
    Screenshot(780),
    SearchAndRescue(785),
    SelfDestruct(790),
    SellDrones(800),
    SellExplorationData(810),
    SellShipOnRebuy(815),
    SendText(820),
    SetUserShipName(825),
    ShieldState(830),
    ShipyardBuy(840),
    ShipyardNew(850),
    ShipyardSell(860),
    ShipyardSwap(870),
    ShipyardTransfer(880),
    StartJump(885),
    SupercruiseEntry(890),
    SupercruiseExit(900),
    Synthesis(910),
    SystemsShutdown(915),
    Touchdown(920),
    Undocked(930),
    USSDrop(940),
    VehicleSwitch(950),
    WingAdd(960),
    WingInvite(965),
    WingJoin(970),
    WingLeave(980)
}

enum class CombatRank(rank: Int) {
    @SerializedName("0")
    Harmless(0),
    @SerializedName("1")
    MostlyHarmless(1),
    @SerializedName("2")
    Novice(2),
    @SerializedName("3")
    Competent(3),
    @SerializedName("4")
    Expert(4),
    @SerializedName("5")
    Master(5),
    @SerializedName("6")
    Dangerous(6),
    @SerializedName("7")
    Deadly(7),
    @SerializedName("8")
    Elite(8)
}

enum class TradeRank(rank: Int) {
    @SerializedName("0")
    Penniless(0),
    @SerializedName("1")
    MostlyPenniless(1),
    @SerializedName("2")
    Peddler(2),
    @SerializedName("3")
    Dealer(3),
    @SerializedName("4")
    Merchant(4),
    @SerializedName("5")
    Broker(5),
    @SerializedName("6")
    Entrepreneur(6),
    @SerializedName("7")
    Tycoon(7),
    @SerializedName("8")
    Elite(8)
}

enum class ExplorationRank(rank: Int) {
    @SerializedName("0")
    Aimless(0),
    @SerializedName("1")
    MostlyAimless(1),
    @SerializedName("2")
    Scout(2),
    @SerializedName("3")
    Surveyor(3),
    @SerializedName("4")
    Explorer(4),
    @SerializedName("5")
    Pathfinder(5),
    @SerializedName("6")
    Ranger(6),
    @SerializedName("7")
    Pioneer(7),
    @SerializedName("8")
    Elite(8)
}

enum class FederationRank(rank: Int) {
    @SerializedName("0")
    None(0),
    @SerializedName("1")
    Recruit(1),
    @SerializedName("2")
    Cadet(2),
    @SerializedName("3")
    Midshipman(3),
    @SerializedName("4")
    PettyOfficer(4),
    @SerializedName("5")
    ChiefPettyOfficer(5),
    @SerializedName("6")
    WarrantOfficer(6),
    @SerializedName("7")
    Ensign(7),
    @SerializedName("8")
    Lieutenant(8),
    @SerializedName("9")
    LtCommander(9),
    @SerializedName("10")
    PostCommander(10),
    @SerializedName("11")
    PostCaptain(11),
    @SerializedName("12")
    RearAdmiral(12),
    @SerializedName("13")
    ViceAdmiral(13),
    @SerializedName("14")
    Admiral(14)
}

enum class EmpireRank(rank: Int) {
    @SerializedName("0")
    None(0),
    @SerializedName("1")
    Outsider(1),
    @SerializedName("2")
    Serf(2),
    @SerializedName("3")
    Master(3),
    @SerializedName("4")
    Squire(4),
    @SerializedName("5")
    Knight(5),
    @SerializedName("6")
    Lord(6),
    @SerializedName("7")
    Baron(7),
    @SerializedName("8")
    Viscount(8),
    @SerializedName("9")
    Count(9),
    @SerializedName("10")
    Earl(10),
    @SerializedName("11")
    Marquis(11),
    @SerializedName("12")
    Duke(12),
    @SerializedName("13")
    Prince(13),
    @SerializedName("14")
    King(14)
}

enum class CQCRank(rank: Int) {
    @SerializedName("0")
    Helpless(0),
    @SerializedName("1")
    MostlyHelpless(1),
    @SerializedName("2")
    Amateur(2),
    @SerializedName("3")
    SemiProfessional(3),
    @SerializedName("4")
    Professional(4),
    @SerializedName("5")
    Champion(5),
    @SerializedName("6")
    Hero(6),
    @SerializedName("7")
    Legend(7),
    @SerializedName("8")
    Elite(8)
}